### ISSUE TITLE
Include javascript as javascript

### ISSUE THREAD

**Issue by micheal-swiggs** [Thiht/markdown-viewer#26]
I wish to use javascript in an md file. I was able to do what I needed by attaching javascript to an onclick attribute of a button. This no longer seems to work. Is there any other way?

**Comment by kribesk** [comment]
Sure it may be. But HTML may also be intentionally malformed and we are ok with it. The main aim of safe parsing is to strip off js code. But in this case it may be unwanted (https://github.com/Thiht/markdown-viewer/issues/26).

As far as I see, this is kind of bug in FF. So FF sanitize does this:
  * does not allow relative links, so links should be resolved manualy before passing to parseFragment
  * does not allow links to local files
This seems nice and reasonable. But I do not know why it does not allow local links from if baseURI is local. Anyway, here is what works if FF allows such links:

~~~~~
function parseHTML(html, rootDocument) {

    var Cc = Components.classes;

    var ioService = Cc["@mozilla.org/network/io-service;1"]
         .getService(Components.interfaces.nsIIOService);

    var baseURI = ioService.newURI(rootDocument.location.href, null, null);

    var parser = Cc["@mozilla.org/xmlextras/domparser;1"]
               .createInstance(Ci.nsIDOMParser);

    parser.init(null, baseURI, baseURI);

    var doc = parser.parseFromString(html, "text/html");

    for (var i = 0; i < doc.links.length; i++)
        doc.links[i].setAttribute("href", doc.links[i].href);

    html = Cc["@mozilla.org/xmlextras/xmlserializer;1"]
         .createInstance(Ci.nsIDOMSerializer)
         .serializeToString(doc.documentElement);

    var parser = Cc["@mozilla.org/parserutils;1"]
         .getService(Ci.nsIParserUtils);

   // this guy strips off hrefs and reports security error in browser console
   return parser.parseFragment(html, 0, 0, baseURI, rootDocument.documentElement);

}
~~~~~

**Comment by Thiht** [comment]
Allowing JS in Markdown files is, I think, a security issue. So no
