### ISSUE TITLE
Support text alignment in tables

### ISSUE THREAD

**Issue by Chadehoc** [Thiht/markdown-viewer#35]
It would be nice if alignment with `:` worked as in
https://help.github.com/articles/github-flavored-markdown/#tables
(currently, always left-aligned)

Example from there:

| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 3 is      | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |

**Comment by klonos** [comment]
1.11 was just made available through AMO and this works like a charm. Thanx! :+1:
