### ISSUE TITLE
Add elementary instructions!

### ISSUE THREAD

**Issue by tallforasmurf** [Thiht/markdown-viewer#41]
I installed the add-on but cannot figure out how to use it. I have a .md file but if I do File>Open, Firefox asks what to do with this? "Open with Xcode (default)", DownThemAll!, Save File?

I cannot see how to get a Firefox window containing .md source, as shown in your screen shot. And if I do, how then do I say, "render this"?

**Comment by NicolasCARPi** [comment]
:+1:

**Comment by regulatre** [comment]
Same problem...

**Comment by Thiht** [comment]
It's supposed to work out of the box the way you use it, something might be broken with the latest versions of Firefox... I'll try to look into it ASAP.

**Comment by NicolasCARPi** [comment]
FYI, it doesn't work with Firefox 39.0.

**Comment by Thiht** [comment]
Duplicate of #36
