### ISSUE TITLE
enhance HTML title

### ISSUE THREAD

**Issue by azrdev** [Thiht/markdown-viewer#43]
As per #5 the HTML title should be the first line of the file. However, if I read https://github.com/Thiht/markdown-viewer/blob/master/chrome/content/markdown-viewer.js#L90 correctly, it is set to the first 50 characters of the file, which yields garbage on short titles.

Moreover, you could parse a pandoc metadata block http://pandoc.org/README.html#metadata-blocks for filling the title field.

**Comment by Thiht** [comment]
The title is defined as: 
* The content of the first h1 found on the document, if there is one (limited to 50 characters)
* Or the first non-empty line (delimited by the line feed character) of the document (limited to 50 characters)

Maybe I'll add a markdown-it plugin or something later for parsing the YAML metadata

**Comment by azrdev** [comment]
very cool, thanks!

We will see if "use the first h1" is a good policy in practice.
