### ISSUE TITLE
Markdown not rendered on multiprocess Firefox

### ISSUE THREAD

**Issue by nnodot** [Thiht/markdown-viewer#46]
Rendering doesn't work when opening a .md file with Firefox developper edition (43.0a2).

I did some debugging that shows that an exception is raised on loading:

```
NS_ERROR_XPC_CANT_PASS_CPOW_TO_NATIVE

It's illegal to pass a CPOW to native code arg 4 [nsIParserUtils.parseFragment]

parseHTML@chrome://markdown-viewer/content/markdown-viewer.js:38:1
MarkdownViewer.onPageLoad@chrome://markdown-viewer/content/markdown-viewer.js:84:20
EventTargetParent.dispatch/<@resource://gre/modules/RemoteAddonsParent.jsm:564:15
Prefetcher.withPrefetching@resource://gre/modules/Prefetcher.jsm:460:14
EventTargetParent.dispatch@resource://gre/modules/RemoteAddonsParent.jsm:560:11
EventTargetParent.receiveMessage@resource://gre/modules/RemoteAddonsParent.jsm:508:1
```

And there are lots of `unsafe CPOW usage` messages in the console.

So, the problem seems to appear with multiprocess versions of Firefox.

I use Markdown Viewer 1.8.1-signed.

According to this [article](http://blog.lassey.us/2015/01/10/unsafe-cpow-usage/) it seems that issues between plugins and CPOW can happen but are solvable. Maybe this [MDN page](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts) contains helpfull informations.

This issue is related to issues [#41](https://github.com/Thiht/markdown-viewer/issues/41) and [#42](https://github.com/Thiht/markdown-viewer/issues/42) but I am creating a new one with a more appropriate title. I hope it's ok!

**Comment by Thiht** [comment]
It's not related to #41 and #42 so no worries :)

I'll try to look into it.

**Comment by andrewgaul** [comment]
This is now an issue with e10s enabled on Firefox 44.0b4 on Linux.

**Comment by Thiht** [comment]
Centralized on #62
