### ISSUE TITLE
Can't open md file in Mac OS X

### ISSUE THREAD

**Issue by KingMario** [Thiht/markdown-viewer#48]
Maybe the file extention is not registered to Firefox in Mac OS X?

**Comment by wasserverein** [comment]
I think I might have the same issue with Debian Stretch and Firefox 38.2.1

If I open a file with extension .md, just the usual download dialogue appears. I was unable to find the relevant Firefox settings, and hence I am unable to view markdown files in the viewer.

**Comment by jhawkinsatgood** [comment]
Same

**Comment by jaywolff** [comment]
Can't open in Firefox 42.0.1 in Arch Linux. Same issue. Warning do not check the box that says "automatically do this with files from now on." It just continually loops opening new tabs until you shutdown firefox..

**Comment by ebergerson** [comment]
I have the same problem on FireFox 42.0 on macos 10.10.5

**Comment by Thiht** [comment]
It should be fixed, can someone try it on **OSX**?

**Comment by ebergerson** [comment]
I don't think it is working on OSX under FireFox yet.  I restarted FIrefox.  I opened Add-ons, it showed the Markdown Viewer.  By the "gear" icon it says no updates found.  I opened the gear pulldown and selected check for updates, it said no updates found.  I then selected view recent updates, and I was told I haven't recently updated any add-ons.   Just to check I dragged an ".md" file to firefox and it tried to open it in XCode.  I then right clicked on the file in FileViewer and explicitly asked it to open the .md file in Firefox, same result, firefox tried to open it in XCode.  Same result if I go to the firefox menu and try to open an .md file using File/Open File...

**Comment by Thiht** [comment]
> By the "gear" icon it says no updates found

Yes, I didn't upload the update yet, sorry I wasn't specific!

Can you uninstall the add-on, restart Firefox, install [this XPI](https://github.com/Thiht/markdown-viewer/releases/tag/v1.9-pre) (the extension file) and give it a try? Firefox might warn you it's not signed, don't worry about that.

**Comment by ebergerson** [comment]
No, why should I worry about that :)

**Comment by ebergerson** [comment]
Works great!  Thanks.

**Comment by Thiht** [comment]
Nice, I close this issue then :)

I'll upload this new version on AMO when I have feedback from more Linux users.

**Comment by wasserverein** [comment]
Tested on 

`Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1`

works very well.

_Thank you!_

**Comment by Thiht** [comment]
I just updated the new version to AMO, it should be updated in a few days if nothing goes wrong. I suggest you switch back to the signed version when it's updated to obtain possible future updates.

(same message as on #36)

**Comment by KingMario** [comment]
It works. Thanks a lot~~~
