### ISSUE TITLE
Non-existent file has unfriendly error page

### ISSUE THREAD

**Issue by andrewgaul** [Thiht/markdown-viewer#58]
![screenshot from 2016-01-22 23 32 57](https://cloud.githubusercontent.com/assets/848247/12529057/7c4bc0e6-c160-11e5-9ab1-ac6b6a896eaa.png)

**Comment by klonos** [comment]
Still seeing this on Windows with 1.10 on latest firefox 47 nightlies.

**Comment by Thiht** [comment]
Confirmed
