### ISSUE TITLE
Can't link past closing parenthesis in URLs

### ISSUE THREAD

**Issue by mica** [Thiht/markdown-viewer#61]
This: 
`[Synecdoche, New York (2008)](http://google.com/search?q=Synecdoche,+New+York+(2008)+imdb&btnI)`

Outputs this: 
[Synecdoche, New York (2008)](http://google.com/search?q=Synecdoche,+New+York+(2008))+imdb&btnI)

Instead of this:
[Synecdoche, New York (2008)](http://google.com/search?q=Synecdoche,+New+York+(2008)+imdb&btnI)

**Comment by Thiht** [comment]
If you use the markdown viewer version on addons.mozilla.org that's "normal". It's fixed since I changed the parser from marked.js to markdown-it. You can use the unsigned release here if you want: https://github.com/Thiht/markdown-viewer/releases

**Comment by mica** [comment]
Is this version going to be released on mozilla.org at some point?

**Comment by Thiht** [comment]
It was rejected last time and I didn't notice it on time...

>Your add-on has been rejected for the following reasons:
>1) Your add-on includes a JavaScript library file that doesn't match our checksums for known release versions. We require all add-ons to use unmodified release versions, obtained directly from the developer's website. Your file `chrome/content/highlight.pack.js` does not match hightlight v8.9.1.
> 2) Established libraries must be included separately, from their official source, in their original format without any modification (changing the file name does not matter). Please note that only stable releases of are acceptable (not beta, pre, RC, dev etc). Minified versions are fine. Please note that third party CDNs are not considered official sources for this purpose. Please use release version of highlight.pack.js from https://github.com/components/highlightjs/releases/

I proposed a new release on AMO earlier today (this version: https://github.com/Thiht/markdown-viewer/releases/tag/1.10) so it should be validated in the coming weeks. For now, you can use the unsigned release, but I strongly suggest you switch again to the signed release as soon as it's available.

**Comment by klonos** [comment]
Let's hope that by "weeks" you mean like a couple of them :smile: ...because in newer versions of firefox (44 and above I think - I'm currently on 47 nightly builds) the ```xpinstall.signatures.required``` option does not work and unsigned versions of extensions are not allowed to be installed.

**Comment by Thiht** [comment]
Oh, that's bad.

It shouldn't be too long though, I'm currently in position "Queue Position: 18 of 29" so it should take a bit more than a week.

**Comment by klonos** [comment]
Yeah, I am very patient. Just wanted to point out the fact that the about:config setting will soon not work (once the official firefox release is 44 and everyone upgrades to it).

**Comment by Thiht** [comment]
The 1.10 just got validated on AMO, they were really quick! As always you can install it from here: https://addons.mozilla.org/fr/firefox/addon/markdown-viewer/ :)

**Comment by klonos** [comment]
Perfect! Confirming this fixed with 1.10. Thanx.
