### ISSUE TITLE
Incompatibility with RightToClick: "window.oldSetTimeout" error on top of file contents.

### ISSUE THREAD

**Issue by klonos** [Thiht/markdown-viewer#64]
```
window.oldSetTimeout=window.setTimeout;window.setTimeout=function(func,delay){return window.oldSetTimeout(function(){try{if(!document.documentElement.getAttribute('stopTimers')){if(typeof func=='string') {var nfunc = new Function(func); nfunc();} else func();}}catch(ex){}},delay);}; window.oldSetInterval=window.setInterval;window.setInterval=function(func,delay){return window.oldSetInterval(function(){try{if(!document.documentElement.getAttribute('stopTimers')){if(typeof func=='string') {var nfunc = new Function(func); nfunc();} else func();}}catch(ex){}},delay);}; Description
```

**Comment by Thiht** [comment]
I don't understand this issue?

**Comment by klonos** [comment]
Take a look at both my screenshots over in https://github.com/Thiht/markdown-viewer/issues/44#issuecomment-188657865

Right before the table that is rendered (the issue with the first line that needs to be empty aside), there's this chunk of output thrown at the very top of the page.

**Comment by simonbcn** [comment]
Same problem:
![seleccion_002](https://cloud.githubusercontent.com/assets/428231/13349663/a2355d4a-dc7b-11e5-981a-b254374d222a.png)

**Comment by Thiht** [comment]
I can't reproduce this issue

Could you provide:
* Your version of Firefox
* Your OS + version
* The content of the Browser Console (`Ctrl+Shift+J`)
* Anything relevant you might think of

**Comment by simonbcn** [comment]
Firefox 44.0.2
Arch Linux 64 bits
Browser console:
```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.1 CONTRIBUTING.md
```

**Comment by klonos** [comment]
Firefox 47 x64 nightly
Windows 8.1 x64

Same error in console as @simonbcn on a clean profile (too many addons that could be interfering installed on my regular profile) with only addon added MDV 1.10

This time (on the clean profile) instead of the error message at the top of the page, I got a completely blank page (no error - no .md content either). This is what is rendered:

```
<html>
  <head>
    <link rel="alternate stylesheet" type="text/css" href="resource://gre-resources/plaintext.css" title="Wrap Long Lines">
  </head>
  <body>
  </body>
</html>
```

**Comment by klonos** [comment]
...tested both local as well as remote .md files.

**Comment by Thiht** [comment]
Does it happen on **every** .md file or just in some particular cases?

**Comment by simonbcn** [comment]
In all .md files.

**Comment by Thiht** [comment]
Ok thanks!
I'll try to reproduce it then, it doesn't occur neither on my Fedora + FF44 nor on my Windows 10 + FF46

**Comment by klonos** [comment]
I can't say that it happens with **ALL** files (because there is no way to actually test that), but it happened consistently with every file I tested. These were both local as well as remote files (for example from various GitHub repos).

**Comment by Thiht** [comment]
It seems this bug isn't really related to Markdown Viewer but to an extension called RightToClick, according to [this StackOverflow answer](http://stackoverflow.com/a/26197882). Could you both confirm you use it?

If you don't, could you check if the problem isn't due to another of your add-ons?

**Comment by klonos** [comment]
I use RightToClick. I'll see if disabling it solves the issue and report back.

**Comment by klonos** [comment]
I just tried a fresh firefox profile with only MDV and RightToClick and all I get when I try to view .md files (various ones from GitHub), all I get is a blank page. Disabling RightToClick and restarting did not solve the issue. Is this another known/reported issue?

**Comment by klonos** [comment]
...never mind. It was multi-process that is enabled by default in firefox. Disabling it made the .md files render properly.

I confirm that enabling RightToClick causes this issue and disabling it makes it go away.

**Comment by Thiht** [comment]
Fixed :)

**Comment by klonos** [comment]
Thanx. Any chance you might roll a new 1.12 release? The sooner you release, the sooner it will be available through AMO (for those of us that use firefox nightlies and cannot install non-signed addons).

Thank you in advance.

**Comment by Thiht** [comment]
Will do ASAP!

Before submitting the 1.12 on AMO I need to figure out why they gave me the following issue with the 1.11 so I can fix it:

>1. Your add-on includes a JavaScript library file that doesn't match any versions known to us. We require all add-ons to use unmodified release versions.

It wasn't blocking for the submission but I want to fix it anyway so I'll have to ask on their IRC.

**Comment by klonos** [comment]
Fair enough, I can wait - no biggie. Thanx once again for fixing the table alignment in 1.11 by the way.

**Comment by Thiht** [comment]
I just submitted the 1.12 on AMO, it should be available soon if everything's ok!

**Comment by klonos** [comment]
Thanx! This thing has been driving me crazy lately.
