### ISSUE TITLE
Links to local files.

### ISSUE THREAD

**Issue by klonos** [Thiht/markdown-viewer#65]
I've just tested 1.10 and #22 is now solved, but it works only with links for non-local files (uploaded to an actual website). Can we please have it work with local files as well (saved on the local file system)?

Thanx for considering this.

**Comment by Thiht** [comment]
I don't really understand the issue, can you be more specific?

For me the following is working as expected:

File test1.md

    [test2](test2.md]

File test2.md

    Hello World!

Although the following, with an absolute path, doesn't seem to be parser:

File test1.md

    [test2](file:///home/thiht/Documents/md/test2.md)

File test2.md

    Hello World!

Is this what you mean?

**Comment by klonos** [comment]
You are right. I was just getting the errors at the top of the page and thought that this was the issue. I didn't notice the link and text at the end of the errors. Keeping #64 open, closing this one here. Sorry for the noise.
