### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Thiht** [Thiht/markdown-viewer#8]
It used to work in previous versions but it's broken with the latest versions of Firefox (probably Firefox 27 or 28) so I removed it for now.
I'll try to figure out how to load a chrome js file after the page loaded.

**Comment by worblehat** [comment]
+1

I really miss syntax highlighting!

**Comment by Thiht** [comment]
Fixed !

**Comment by worblehat** [comment]
Thank you very much!
